# Generated by Django 3.0.2 on 2020-11-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('position_name', models.CharField(max_length=100)),
                ('hire_date', models.DateField(verbose_name='Дата приёма на работу')),
                ('fire_date', models.DateField(default=None, verbose_name='Дата увольнения')),
                ('salary', models.IntegerField(verbose_name='руб')),
                ('fraction', models.IntegerField(verbose_name='%')),
                ('base', models.IntegerField(verbose_name='%')),
                ('advance', models.IntegerField(verbose_name='%')),
                ('by_hours', models.BooleanField()),
            ],
        ),
    ]
