# Generated by Django 3.0.2 on 2020-11-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_auto_20201104_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='fire_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
